
import './global.css'

import localFont from 'next/font/local'

import { Metadata } from 'next'


// Font files can be colocated inside of `app`
const roclette = localFont({
  src: './fonts/RoclettePro-Normal.woff2',
  variable: '--font-roclette',
})

const rocletteBold = localFont({
  src: './fonts/RoclettePro-Bold.woff2',
  variable: '--font-roclette-bold',
})

const rocletteSBoldItalic= localFont({
  src: './fonts/RocletteProItalic-SBoldItalic.woff2',
  variable: '--font-roclette-sbold',
})


const ottenburgDisplaySBold = localFont({
  src: './fonts/ottenburgDisplay-SemiBold.woff2',
  variable: '--font-ottenburg-sbold',
})

const ottenburgDisplay = localFont({
  src: './fonts/ottenburgDisplay-Regular.woff2',
  variable: '--font-ottenburg',
})

const economicaBold = localFont({
  src: './fonts/Economica-Bold.ttf',
  variable: '--font-eco-bold',
})



export const metadata : Metadata = {
  title: 'Antoine Familiar - portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={` bg-[#D3D3D3] ${economicaBold.variable} ${roclette.variable} ${rocletteBold.variable} ${rocletteSBoldItalic.variable} ${ottenburgDisplay.variable} ${ottenburgDisplaySBold.variable}`}>
      <body className='overflow-x-hidden'>{children}</body>
    </html>
  );
}
 